version: "3.5"
services:
  node:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - ./build/cli.node.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - '${MNEMONIC}'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug